import React, { useState } from 'react';
import { Printer, MessageSquare } from 'lucide-react';
import { useApp } from '../../context/AppContext';

export const PdfQuoteDispatcherTab: React.FC = () => {
  const { equipmentEnquiries, showToast } = useApp();
  const [selectedEnquiry, setSelectedEnquiry] = useState<any | null>(null);

  // Pricing Inputs
  const [unitPrices, setUnitPrices] = useState<Record<string, number>>({});
  const [discountPercent, setDiscountPercent] = useState<number>(5);
  const [freightCharges, setFreightCharges] = useState<number>(3500);
  const [gstPercent, setGstPercent] = useState<number>(18);

  const handleOpenQuoteGenerator = (enquiry: any) => {
    setSelectedEnquiry(enquiry);
    // Initialize unit prices
    const initial: Record<string, number> = {};
    enquiry.selectedProducts.forEach((item: any) => {
      initial[item.id] = 45000; // Default B2B Wholesale base price placeholder
    });
    setUnitPrices(initial);
  };

  const handleUnitPriceChange = (productId: string, val: number) => {
    setUnitPrices(prev => ({ ...prev, [productId]: Math.max(0, val) }));
  };

  // Math calculations
  const calculateTotals = () => {
    if (!selectedEnquiry) return { subtotal: 0, discount: 0, freight: 0, gst: 0, grandTotal: 0 };

    let subtotal = 0;
    selectedEnquiry.selectedProducts.forEach((item: any) => {
      const price = unitPrices[item.id] || 45000;
      subtotal += price * item.quantity;
    });

    const discount = (subtotal * discountPercent) / 100;
    const taxable = subtotal - discount + freightCharges;
    const gst = (taxable * gstPercent) / 100;
    const grandTotal = taxable + gst;

    return { subtotal, discount, freight: freightCharges, gst, grandTotal };
  };

  const totals = calculateTotals();

  const handleSendWhatsApp = () => {
    if (!selectedEnquiry) return;
    const cleanPhone = selectedEnquiry.mobile.replace(/[^0-9]/g, '');
    const message = encodeURIComponent(
      `Hello ${selectedEnquiry.name},\n\n` +
        `Official B2B Price Quotation [${selectedEnquiry.rfqReference}] for *${selectedEnquiry.companyGymName}* has been generated by Tanush Fitness!\n\n` +
        `*Quotation Grand Total:* ₹${totals.grandTotal.toLocaleString('en-IN')}\n` +
        `*Items:* ${selectedEnquiry.selectedProducts.length} Equipment Models\n` +
        `*GST (18%):* Included\n\n` +
        `Our executive team is available for dispatch scheduling. Thank you!`
    );

    window.open(`https://wa.me/91${cleanPhone}?text=${message}`, '_blank');
    showToast(`WhatsApp quotation message generated for ${selectedEnquiry.mobile}`);
  };

  return (
    <div className="space-y-6 font-mono text-xs">
      <div className="bg-white p-4 rounded-2xl border border-slate-200 shadow-sm flex items-center justify-between">
        <div>
          <h3 className="text-sm font-black text-slate-900 font-heading uppercase">
            B2B PDF Quotation Generator & Dispatcher
          </h3>
          <p className="text-[10px] text-slate-500 font-normal">
            Convert incoming RFQ enquiries into formal itemized price quotes with discounts & GST.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* RFQ Enquiries List */}
        <div className="lg:col-span-5 space-y-3">
          <div className="text-xs font-black uppercase text-slate-700 font-heading">
            Pending RFQs ({equipmentEnquiries.length})
          </div>

          {equipmentEnquiries.length === 0 ? (
            <div className="p-8 text-center bg-white rounded-2xl border border-slate-200 text-slate-400">
              No RFQ enquiries submitted yet.
            </div>
          ) : (
            equipmentEnquiries.map(rfq => (
              <div
                key={rfq.id}
                onClick={() => handleOpenQuoteGenerator(rfq)}
                className={`p-4 rounded-2xl border cursor-pointer transition-all ${
                  selectedEnquiry?.id === rfq.id
                    ? 'bg-blue-50/70 border-blue-600 shadow-md'
                    : 'bg-white border-slate-200 hover:border-slate-300'
                }`}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="text-[10px] font-bold text-blue-600 font-mono">{rfq.rfqReference}</span>
                  <span className="text-[9px] font-bold px-2 py-0.5 rounded bg-blue-100 text-blue-900 uppercase">
                    {rfq.status}
                  </span>
                </div>
                <div className="font-black text-slate-900 font-heading uppercase text-sm">{rfq.companyGymName}</div>
                <div className="text-[11px] text-slate-600">{rfq.name} • {rfq.mobile}</div>
                <div className="text-[10px] text-slate-500 mt-2 font-bold">
                  Items Requested: {rfq.selectedProducts.length} Models
                </div>
              </div>
            ))
          )}
        </div>

        {/* Pricing Calculator & PDF Preview */}
        <div className="lg:col-span-7">
          {selectedEnquiry ? (
            <div className="bg-white rounded-3xl border border-slate-200 p-6 space-y-6 shadow-sm">
              <div className="flex items-center justify-between border-b border-slate-100 pb-3">
                <div>
                  <span className="text-[10px] font-bold text-blue-600 uppercase font-mono">
                    RFQ: {selectedEnquiry.rfqReference}
                  </span>
                  <h3 className="text-base font-black text-slate-900 font-heading uppercase">
                    {selectedEnquiry.companyGymName}
                  </h3>
                </div>
                <div className="text-right text-xs">
                  <div className="font-bold text-slate-900">{selectedEnquiry.name}</div>
                  <div className="text-blue-600 font-bold">{selectedEnquiry.mobile}</div>
                </div>
              </div>

              {/* Item Pricing Matrix */}
              <div className="space-y-3">
                <div className="text-xs font-black uppercase text-slate-700">
                  Itemized Wholesale Unit Pricing
                </div>

                <div className="space-y-2 divide-y divide-slate-100">
                  {selectedEnquiry.selectedProducts.map((item: any) => (
                    <div key={item.id} className="pt-2 flex items-center justify-between gap-3">
                      <div>
                        <div className="font-bold text-slate-900 uppercase">{item.name}</div>
                        <div className="text-[10px] text-slate-500">Qty: {item.quantity} Units</div>
                      </div>

                      <div className="flex items-center gap-2">
                        <span className="text-slate-500 font-bold">₹/unit:</span>
                        <input
                          type="number"
                          value={unitPrices[item.id] || 45000}
                          onChange={e => handleUnitPriceChange(item.id, parseFloat(e.target.value))}
                          className="w-28 bg-slate-50 border border-slate-200 rounded-xl p-1.5 text-xs font-bold text-right text-slate-900"
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Adjustments (Discount, Freight, GST) */}
              <div className="grid grid-cols-3 gap-3 pt-3 border-t border-slate-100">
                <div>
                  <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Discount %</label>
                  <input
                    type="number"
                    value={discountPercent}
                    onChange={e => setDiscountPercent(parseFloat(e.target.value) || 0)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2 text-xs font-bold text-slate-900"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">Freight Charges (₹)</label>
                  <input
                    type="number"
                    value={freightCharges}
                    onChange={e => setFreightCharges(parseFloat(e.target.value) || 0)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2 text-xs font-bold text-slate-900"
                  />
                </div>

                <div>
                  <label className="text-[10px] font-bold text-slate-500 uppercase block mb-1">GST Tax %</label>
                  <input
                    type="number"
                    value={gstPercent}
                    onChange={e => setGstPercent(parseFloat(e.target.value) || 0)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-xl p-2 text-xs font-bold text-slate-900"
                  />
                </div>
              </div>

              {/* Calculated Totals Summary */}
              <div className="p-4 bg-slate-900 text-white rounded-2xl space-y-1.5">
                <div className="flex justify-between text-xs text-slate-300">
                  <span>Subtotal:</span>
                  <span>₹{totals.subtotal.toLocaleString('en-IN')}</span>
                </div>
                <div className="flex justify-between text-xs text-emerald-400 font-bold">
                  <span>Discount ({discountPercent}%):</span>
                  <span>- ₹{totals.discount.toLocaleString('en-IN')}</span>
                </div>
                <div className="flex justify-between text-xs text-slate-300">
                  <span>Freight & Handling:</span>
                  <span>+ ₹{totals.freight.toLocaleString('en-IN')}</span>
                </div>
                <div className="flex justify-between text-xs text-blue-400 font-bold">
                  <span>GST ({gstPercent}%):</span>
                  <span>+ ₹{totals.gst.toLocaleString('en-IN')}</span>
                </div>
                <div className="flex justify-between text-base font-black text-white pt-2 border-t border-slate-800">
                  <span>Grand Total:</span>
                  <span className="text-amber-400">₹{totals.grandTotal.toLocaleString('en-IN')}</span>
                </div>
              </div>

              {/* Action Buttons: Dispatch via WhatsApp */}
              <div className="grid grid-cols-2 gap-3">
                <button
                  onClick={handleSendWhatsApp}
                  className="py-3 px-4 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-black uppercase flex items-center justify-center gap-2 shadow-md"
                >
                  <MessageSquare className="w-4 h-4" />
                  <span>Send via WhatsApp</span>
                </button>

                <button
                  onClick={() => {
                    window.print();
                    showToast('PDF Quotation ready for download/print');
                  }}
                  className="py-3 px-4 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-black uppercase flex items-center justify-center gap-2 shadow-md"
                >
                  <Printer className="w-4 h-4" />
                  <span>Print / Save PDF</span>
                </button>
              </div>
            </div>
          ) : (
            <div className="p-12 text-center bg-white rounded-3xl border border-slate-200 text-slate-400">
              Select an RFQ enquiry on the left to generate quotation & dispatch via WhatsApp.
            </div>
          )}
        </div>
      </div>
    </div>
  );
};
